FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/billing ./services/billing/cmd

FROM scratch
COPY --from=builder /bin/billing /billing
ENTRYPOINT ["/billing"]
